// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Live_Server
{
    internal sealed partial class Vsix
    {
        public const string Id = "Live_Server.1bee55e6-e1d5-47ea-8ffe-50444861529e";
        public const string Name = "Live_Server";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu kumar Sharma";
        public const string Tags = "";
    }
}
