// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Live_Server
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string Live_ServerString = "aea8da49-042d-479c-8ba2-50c8f777372e";
        public static Guid Live_Server = new Guid(Live_ServerString);

        public const string Live_Server_OncommandString = "aea8da49-042d-479c-8ba2-50c8f777373e";
        public static Guid Live_Server_Oncommand = new Guid(Live_Server_OncommandString);

        public const string Live_Server_OffcommandString = "aea8da49-042d-479c-8ba2-50c8f777379e";
        public static Guid Live_Server_Offcommand = new Guid(Live_Server_OffcommandString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0103;
        public const int OnCommand = 0x0101;
        public const int OffCommand = 0x0102;
    }
}